version: 2.1

commands:
  install-packages:
    steps:
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps2.1-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements.txt" }}
      - run: pip install --upgrade pip
      - run: # install and activate virtual environment with pip
          name: Install python app dependencies
          command: pip install -r requirements-dev.txt
      - save_cache: # ** special step to save dependency cache **
          key: deps2.1-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "~/.local/bin"
            - "~/.local/lib"

jobs:
  test:
    docker:
      # python container
      - image: cimg/python:3.8
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: circle_test
          DB_USERNAME: postgres
      # Service container image
      - image: cimg/postgres:11.12
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - install-packages
      - run: coverage run --source=./zeus/ ./manage.py test --junit-xml=test_results/test.xml zeus/
      - run: coverage xml
      - run: bash <(curl -s https://codecov.io/bash) -X html
      - store_test_results:
          path: test_results
  formatting:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - install-packages
      - run: black --check ./
      - run: isort . -c

workflows:
  test-workflow:
    jobs:
      - test
      - formatting

